# Generated by Django 3.2.10 on 2024-07-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20240615_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='name',
        ),
    ]
