# Generated by Django 3.2.10 on 2024-07-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_packing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
